# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除'), (10, '精华')], verbose_name='状态'),
        ),
    ]
