# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20160711_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, verbose_name='头像'),
        ),
    ]
